### ISSUE TITLE
Deduplicate entries on the server side to guarantee idempotency

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/hastory#14]
This could be done using content-addressable entries.
@yigitozkavci

**Comment by StevenXL** [comment]
@NorfairKing I'd like to work on this in the coming week. Do you have any thoughts on implementation?

I was thinking of adding a new field to [ServerEntry](https://github.com/NorfairKing/hastory/blob/ad9e8ff9551ae05f006ad0a9a2103771a2017fac/hastory-server-data/src/Hastory/Server/Data.hs#L22). I'd make an instance of [Hashable](https://hackage.haskell.org/package/hashable-1.3.0.0/docs/Data-Hashable.html) for [SyncRequest](https://github.com/NorfairKing/hastory/blob/ad9e8ff9551ae05f006ad0a9a2103771a2017fac/hastory-data/src/Data/Hastory/Types/SyncRequest.hs#L15), and we would save SyncRequest's hash in our `ServerEntry`. Our single endpoint would search for a `ServerEntry` with that hash to determine if it is receiving duplicate data.

**Comment by NorfairKing** [comment]
> @NorfairKing I'd like to work on this in the coming week. Do you have any thoughts on implementation?

@StevenXL Sounds great! I look forward to your work.

> I was thinking of adding a new field to [ServerEntry](https://github.com/NorfairKing/hastory/blob/ad9e8ff9551ae05f006ad0a9a2103771a2017fac/hastory-server-data/src/Hastory/Server/Data.hs#L22) - something like `contentHash`. I'd make an instance of [Hashable](https://hackage.haskell.org/package/hashable-1.3.0.0/docs/Data-Hashable.html) for [SyncRequest](https://github.com/NorfairKing/hastory/blob/ad9e8ff9551ae05f006ad0a9a2103771a2017fac/hastory-data/src/Data/Hastory/Types/SyncRequest.hs#L15), and we would save SyncRequest's hash in our `ServerEntry`. Our single endpoint would search for a `ServerEntry` with that hash to determine if it is receiving duplicate data.

I don't think it's a great idea to have that instance.
Instead you probably want to do something like this (pseudocode):

```
hashEntry :: Each -> Field -> Of -> Entry -> As -> An -> Argument -> Sha256Hash
```

The reason is that:
- An instance instead of a function doesn't buy you anything
- The sync request will contain more than one entry in the near future.
See #13

**Comment by NorfairKing** [comment]
Implemented in #26

**Comment by StevenXL** [comment]
@NorfairKing thank you for all your help on #26. I think we're good to close this issue.

**Comment by NorfairKing** [comment]
Jup!
