### ISSUE TITLE
Store the server-side entries in a(n sqlite) database

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/hastory#16]
@yigitozkavci

**Comment by NorfairKing** [comment]
@yigitozkavci I think this is the best issue to proceed with next.

**Comment by yigitozkavci** [comment]
I'll work on this in the following weekend. Hopefully this shouldn't be too complex

**Comment by NorfairKing** [comment]
Should be fine! Let me know if you need any help. You can find inspiration in the smos-sync-client or donna-cli source code.

**Comment by StevenXL** [comment]
Hi @NorfairKing I would like to take this issue on myself. It seems similar enough to my work on #9. I'll shouldn't take me more than until next Friday to find the time.

**Comment by NorfairKing** [comment]
@StevenXL Cool!
