### ISSUE TITLE
Store database in hastory specific data dir

### ISSUE THREAD

**Issue by StevenXL** [NorfairKing/hastory#36]
Please see #33 for background, but to summarize, we are currently storing the database in the same directory as the `Settings`'s cache dir. This is dangerous, as a it is common to delete caches. 

Instead, we should store the database in a more permanent directory. As a first pass, we should try to adhere to [XDG guidelines](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for where applications should store user data. `path-io` makes this easy via the use of [getAppUserDataDir](https://hackage.haskell.org/package/path-io-1.6.0/docs/Path-IO.html#v:getAppUserDataDir).

**Comment by StevenXL** [comment]
@NorfairKing I think this is a duplicate of #28

**Comment by NorfairKing** [comment]
@StevenXL In practice yes.
