### ISSUE TITLE
Add `hastory path`

### ISSUE THREAD

**Issue by StevenXL** [NorfairKing/hastory#52]
It would be nice for the user to have a quick and easy way to see what paths hastory is using, much like `stack path`. This would clean up the `README.md` a bit, would be more user-friendly, and we'd have an easier time maintaining the `README.md` since we can just ask the user to run `hastory path`.

**Comment by NorfairKing** [comment]
XDG is a standard. We can get away with just using XDG and be done with it I think.

**Comment by StevenXL** [comment]
Sounds good to me.
