### ISSUE TITLE
A simple append-only sync server

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/hastory#7]
It would be nice to be able to gather commands to a centralised server.
Both for surveillance, auditability and for archiving.

**Comment by yigitozkavci** [comment]
Hi there. I'm up for the task, and here is how I plan to do it, feel free let me know if any of it doesn't make sense:

- A new executable called `hastory-server` will be introduced in the existing `hastory` package. Upon executing, `hastory-server` will start listening for commands on a port given to it as a flag and it will store the commands in `~/.hastory`. This binary is meant to be run in the aforementioned centralised server.
- Existing hastory package will accept a flag for knowing about the centralised `hastory-server`, if any. If it knows about the server, it will try to send commands to this server. This operation should be perfomed in background and fail-open. It shouldn't have an impact on existing workflows.

**Comment by NorfairKing** [comment]
Hi @yigitozkavci That sounds great!

> A new executable called hastory-server will be introduced in the existing hastory package. 

Not a new executable in the same package, but a new package in the same repository.
There's no need to compile a server if you only want the CLI.

The rest sounds exactly right.

**Comment by yigitozkavci** [comment]
> Not a new executable in the same package, but a new package in the same repository.
There's no need to compile a server if you only want the CLI.

As soon as I started with the implementation I realized this, yes. It will be a third package, along with `hastory` and `hastory-test-utils`.

**Comment by NorfairKing** [comment]
I recommend using servant for the server, it will make things much easier for you.i also recommend giving each entry a uuid for reduplication in case of retries.

**Comment by NorfairKing** [comment]
Hi @yigitozkavci , just to be sure: base your work off the latest master/development.

**Comment by yigitozkavci** [comment]
@NorfairKing Oh, thanks. It looks like my branch is 24 commits behind the master: 
https://github.com/yigitozkavci/hastory/tree/hastory-server

I'll rebase when I get back working on it.

**Comment by yigitozkavci** [comment]
Hmm, data storage doesn't really affect server or client implementation. Client only sends a command append request to server in the background. We don't read anything from the storage.

But of course, I will rebase before adding more code into my hastory-server branch.

**Comment by NorfairKing** [comment]
@yigitozkavci Ok cool.
One concern that I have is deduplication.
Ideally, I'd like the server to not store duplicate entries in case the client sends it over multiple times.
This likely means that the server has to deduplicate them using content-addressable storage or so.
Anyway, I'll leave the details up to you, I'm sure you will have better ideas than I do.

**Comment by yigitozkavci** [comment]
Hi @NorfairKing,

My server-client implementation is done in terms of it's minimal functionality (there are ~10 TODOs that I'll address before opening a PR).

I've got a couple of questions:
- In terms of storage format I'm thinking of CSV, since we want this to be append-only. JSON is not the best choice for appending as it requires loading the whole data into memory for format-aware appending.
- I'm using the primary keys of database entries for uniquely identifying them in the server but it seems like entries are always inserted into database, not upserted, making sending keys from client to server obsolete. Is this intended?

**Comment by NorfairKing** [comment]
@yigitozkavci 

About the storage format:
I was thinking about sqlite. As far as databases go it's usually the simplest tool.
At the moment the server will only be storing the logs, not processing them or searching them (yet).

About the deduplicating:
You're right, I think we'll need the client to store the server-side key of the things they've sent over, after acknowledgement, to make sure that each entry is sent to the client at least once.
On the server side we may want to make the entries content-addressable so that they are stored at-most once.

**Comment by yigitozkavci** [comment]
> For the first version you can forget about the deduplication, if that makes things simpler.

It's fine either way, really. Just wanted to clarify the source of truth data. We can either treat client or server as the source of truth.

To make things less complicated and intuitive for the user, I'm inclined to keep server as just a log keeper for now. Currently we already save the data to local sqlite and I'm sending this command along with it's row id to the server for appending.

To repeat my question earlier, is it indended for sqlite to be duplicating entries in the current implementation? I thought it would update the command if it already exists in the database.

**Comment by NorfairKing** [comment]
> To make things less complicated and intuitive for the user, I'm inclined to keep server as just a log keeper for now. 

Well the idea is to make the server a collector, in case the clients lose their data.

> To repeat my question earlier, is it indended for sqlite to be duplicating entries in the current implementation? I thought it would update the command if it already exists in the database.

Yes it is intended to duplicate _commands_ but not entries. Entries include the timestamp, and those should not be duplicated.
